		<title> <?php echo $title ?> </title>
		<?php foreach($sheets as $sheet) { extract($sheet); ?>
			<?php echo "<link href='".$sheetTarget."'rel='stylesheet'>" ?>
		<?php } ?>
	</head>
	<body class="hom">
	<?php foreach($scripts as $script) { extract($script); ?>
		<?php echo "<script type='text/javascript' charset='UTF-8' src='".$scriptPath."'>.</script>" ?>
	<?php } ?>
		<div id="wrap">	
			<div id="left-wrap">
				<div id="left">
					<div id="left-left">
						<div id="paw1" class="paw">
							<a href="<?php echo $subpageUrl1 ?>" id="paw-option-1">
								<div id="pad1" class="pad">
									<p id="pad-option-1" class="pad-option"> <?php echo $subpageText1 ?> </p>
									<div id="imgUrl1" class="alter-pad"></div>
									<div class="toe1 toe"></div>
									<div class="toe2 toe"></div>
									<div class="toe3 toe"></div>
									<div class="toe4 toe"></div>
								</div>
							</a>
						</div>
						<div id="left-left-down">
							<div id="paw2" class="paw">
								<a href="<?php echo $subpageUrl2 ?>" id="paw-option-2">
									<div id="pad2" class="pad">
										<p id="pad-option-2" class="pad-option"><?php echo $subpageText2 ?> </p>
										<div id="imgUrl2" class="alter-pad"></div>
										<div class="toe1 toe"></div>
										<div class="toe2 toe"></div>
										<div class="toe3 toe"></div>
										<div class="toe4 toe"></div>
									</div>
								</a>
							</div>
						</div>
					</div>
					<div id="left-right">
						<div id="paw3" class="paw">
							<a href="<?php echo $subpageUrl3 ?>" id="paw-option-3">
								<div id="pad3" class="pad">
									<p id="pad-option-3" class="pad-option"><?php echo $subpageText3 ?> </p>
									<div id="imgUrl3" class="alter-pad"></div>
									<div class="toe1 toe"></div>
									<div class="toe2 toe"></div>
									<div class="toe3 toe"></div>
									<div class="toe4 toe"></div>
								</div>
							</a>
						</div>
						<div id="left-right-down">
							<div id="paw4" class="paw">
								<a href="<?php echo $subpageUrl4 ?>" id="paw-option-4">
									<div id="pad4" class="pad">
										<p id="pad-option-4" class="pad-option"><?php echo $subpageText4 ?> </p>
										<div id="imgUrl4" class="alter-pad"></div>
										<div class="toe1 toe"></div>
										<div class="toe2 toe"></div>
										<div class="toe3 toe"></div>
										<div class="toe4 toe"></div>
									</div>
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div id="right-wrap">
				<div id="right">
					<a href= <?php echo "'".$homePage."'" ?>>
						<div id="top-logo-wrap">
							<div id="top-logo" class="logo">
								<p id="logo-title"> <?php echo $logoText ?></p>
							</div>
						</div>
					</a>
					<div id="text-wrap"></div>
				</div>
			</div>