<!DOCTYPE html>
<html> 
	<head>
		<meta charset="utf-8">
		<?php foreach($sheets as $sheet) { extract($sheet); ?>
			<?php echo "<link href='".$cssPath."'rel='stylesheet'>" ?>
		<?php } ?>
		<script type="text/javascript" src="../lib/jquery-1.12.1.min.js"> </script>
		<title> <?php echo $title ?> </title>
	</head>
	<body class="hom">
	<?php foreach($scripts as $script) { extract($script); ?>
		<?php echo "<script type='text/javascript' charset='UTF-8' src='".$scriptPath."'>.</script>" ?>
	<?php } ?>
		<div id="wrap">	
			<div id="left-wrap">
				<div id="left">
					<div id="left-left">
						<div id="paw1" class="paw">
							<a href="#" id="paw-option-1">
								<div id="pad1" class="pad">
									<p id="pad-option-1" class="pad-option"> <?php echo $padOption1 ?> </p>
									<div id="alter-pad1" class="alter-pad"></div>
									<div class="toe1 toe"></div>
									<div class="toe2 toe"></div>
									<div class="toe3 toe"></div>
									<div class="toe4 toe"></div>
								</div>
							</a>
						</div>
						<div id="left-left-down">
							<div id="paw2" class="paw">
								<a href="#" id="paw-option-2">
									<div id="pad2" class="pad">
										<p id="pad-option-2" class="pad-option"><?php echo $padOption2 ?> </p>
										<div id="alter-pad2" class="alter-pad"></div>
										<div class="toe1 toe"></div>
										<div class="toe2 toe"></div>
										<div class="toe3 toe"></div>
										<div class="toe4 toe"></div>
									</div>
								</a>
							</div>
						</div>
					</div>
					<div id="left-right">
						<div id="paw3" class="paw">
							<a href="#" id="paw-option-3">
								<div id="pad3" class="pad">
									<p id="pad-option-3" class="pad-option"><?php echo $padOption3 ?> </p>
									<div id="alter-pad3" class="alter-pad"></div>
									<div class="toe1 toe"></div>
									<div class="toe2 toe"></div>
									<div class="toe3 toe"></div>
									<div class="toe4 toe"></div>
								</div>
							</a>
						</div>
						<div id="left-right-down">
							<div id="paw4" class="paw">
								<a href="#" id="paw-option-4">
									<div id="pad4" class="pad">
										<p id="pad-option-4" class="pad-option"><?php echo $padOption4 ?> </p>
										<div id="alter-pad4" class="alter-pad"></div>
										<div class="toe1 toe"></div>
										<div class="toe2 toe"></div>
										<div class="toe3 toe"></div>
										<div class="toe4 toe"></div>
									</div>
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div id="right-wrap">
				<div id="right">
					<div id="top-logo-wrap">
						<div id="top-logo" class="logo">
							<p id="logo-title"> <?php echo $logo_title ?></p>
						</div>
					</div>
					<div id="text-wrap"></div>
				</div>
			</div>
			<div id="footer">©<?php echo date("Y")?> Xsignati.</div>
		</div>
	</body>
</html>
